[profile.release]
panic = 'unwind'

[workspace]
members = [
    # 'node',
    'pallets/equilibrium-curve-amm',
    'pallets/equilibrium-curve-amm/rpc',
    'pallets/equilibrium-curve-amm/rpc/runtime-api',
    # 'runtime',
]
